 
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bracumon/repositories/montol_tori_website_full
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp achivements.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp join.html $DEPLOYPATH
    - /bin/cp outreach.html $DEPLOYPATH
    - /bin/cp sponsor.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
